Bugfix/pagination
shopengine/nova pull request #2
Opened 2022-11-07 11:43 UTC by luebbt

Teil 1 zu https://reishunger.atlassian.net/browse/WEB-1454

2022-11-08 15:42 UTC, simonReishunger requested changes

2022-11-08 15:42 UTC, simonReishunger commented on src/Api/ListRequestBuilder.php
> +    protected function paginator($items, $total, $perPage, $currentPage, $options)
wurde der return type gewollt entfernt?

2022-11-08 16:27 UTC, luebbt commented on src/Api/ListRequestBuilder.php
> +    protected function paginator($items, $total, $perPage, $currentPage, $options)
Ne, hab den neuen hinzugefügt.

2022-11-09 12:03 UTC, simonReishunger approved these changes

2022-11-09 12:06 UTC, merged